'use strict';

const {Resend}=require('resend');
const jwt=require('jsonwebtoken');
const logger=require('../utils/logger');
const resend=new Resend(process.env.RESEND_API_KEY);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function sender(){return process.env.SENDER_EMAIL?`${process.env.SENDER_NAME||'PakkOrder'} <${process.env.SENDER_EMAIL}>`:'PakkOrder <onboarding@resend.dev>';}
async function sendConfirmationEmail({buyerEmail,storeName,orderDetails,orderId,storeOrderId,clientId}){if(!buyerEmail)return;try{const token=jwt.sign({orderId,clientId,action:'pending'},process.env.JWT_SECRET,{expiresIn:'24h'});const confirmUrl=`${process.env.APP_URL}/confirm?token=${token}&action=confirm`,cancelUrl=`${process.env.APP_URL}/confirm?token=${token}&action=cancel`;const html=`<div style="font-family:Arial;max-width:560px;margin:auto"><h2>${esc(storeName)}</h2><p>Please confirm your COD order <strong>#${esc(storeOrderId||orderId)}</strong>.</p><p>${esc(orderDetails)}</p><p><a href="${confirmUrl}">Confirm order</a> · <a href="${cancelUrl}">Cancel order</a></p><small>Confirmation links expire after 24 hours.</small></div>`;const {error}=await resend.emails.send({from:sender(),to:buyerEmail,subject:`${storeName} — Confirm your order`,html});if(error)logger.error(`Resend send failed for order ${orderId}: ${error.message||JSON.stringify(error)}`);}catch(e){logger.error(`sendConfirmationEmail failed for order ${orderId}`,e);}}
async function sendContactNotification({fullName,email,phone,website,monthlyOrders,message,referralCode}){try{const to=process.env.CONTACT_NOTIFY_EMAIL;if(!to){logger.warn('CONTACT_NOTIFY_EMAIL not configured — skipping contact notification');return;}const html=`<h2>New PakkOrder enquiry</h2><p><b>Name:</b> ${esc(fullName)}</p><p><b>Email:</b> ${esc(email)}</p><p><b>Phone:</b> ${esc(phone)}</p><p><b>Website:</b> ${esc(website)}</p><p><b>Monthly orders:</b> ${esc(monthlyOrders)}</p><p><b>Referral:</b> ${esc(referralCode||'-')}</p><p>${esc(message||'')}</p>`;const {error}=await resend.emails.send({from:sender(),to,subject:`New PakkOrder enquiry: ${fullName}`,html,replyTo:email});if(error)logger.error('sendContactNotification failed',error);}catch(e){logger.error('sendContactNotification threw',e);}}
function csvBuffer(orders){const cols=['Order ID','Buyer Name','Phone','City','Amount','Status'];const rows=orders.map(o=>[o.order_id||'',o.buyer_name||'',o.buyer_phone||'',o.buyer_city||'',o.order_amount||'',o.status||''].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','));return Buffer.from([cols.join(','),...rows].join('\n'),'utf8');}
async function sendMonthlyReport(client,orders,monthName,year){if(!client.email)return;try{const total=orders.length,confirmed=orders.filter(o=>o.status==='confirmed').length,cancelled=orders.filter(o=>o.status==='cancelled').length,expired=orders.filter(o=>o.status==='expired').length;const html=`<div style="font-family:Arial"><h2>PakkOrder — ${esc(monthName)} ${year}</h2><p>${esc(client.name||'Store')}</p><p>Total: <b>${total}</b> · Confirmed: <b>${confirmed}</b> · Cancelled: <b>${cancelled}</b> · Expired: <b>${expired}</b></p><p>Your order export is attached.</p></div>`;const {error}=await resend.emails.send({from:sender(),to:client.email,subject:`Your PakkOrder Report — ${monthName} ${year}`,html,attachments:[{filename:`pakkorder-${String(monthName).toLowerCase()}-${year}.csv`,content:csvBuffer(orders).toString('base64')}]});if(error)logger.error(`sendMonthlyReport failed for ${client.id}`,error);}catch(e){logger.error(`sendMonthlyReport threw for ${client.id}`,e);}}
module.exports={sendConfirmationEmail,sendContactNotification,sendMonthlyReport};
