'use strict';

const admin = require('firebase-admin');
const logger = require('../utils/logger');
const db = admin.firestore();
const PLAN_LIMITS = { starter: 200, growth: 500, advanced: 1000, pro: 2000, business: 999999 };
const now = () => admin.firestore.Timestamp.now();
const fromDate = date => admin.firestore.Timestamp.fromDate(date);

async function firstBy(field,value,collection='clients') { const s=await db.collection(collection).where(field,'==',value).limit(1).get(); return s.empty?null:{id:s.docs[0].id,...s.docs[0].data()}; }
async function getClientByLicenseKey(v){try{return await firstBy('license_key',v);}catch(e){logger.error('getClientByLicenseKey failed',e);throw e;}}
async function getClientByDomain(v){return firstBy('domain',v);}
async function getClientByMyshopifyDomain(v){return firstBy('myshopify_domain',v);}
async function getClientById(id){const d=await db.collection('clients').doc(id).get();return d.exists?{id:d.id,...d.data()}:null;}
async function createClient(data){const plan=data.plan||'starter';const r=await db.collection('clients').add({name:data.name,email:data.email,phone:data.phone,domain:data.domain,license_key:data.license_key,auth_uid:data.auth_uid||null,plan,whatsapp_number:data.whatsapp_number||'shared',wa_phone_number_id:data.wa_phone_number_id||null,wa_access_token:data.wa_access_token||null,orders_this_month:0,order_limit:PLAN_LIMITS[plan]||PLAN_LIMITS.starter,is_active:true,trial_active:data.trial_active||false,trial_ends_at:data.trial_ends_at||null,created_at:now(),updated_at:now()});return r.id;}
async function updateClientFields(id,fields){await db.collection('clients').doc(id).update({...fields,updated_at:now()});}
async function getAllClients(){const s=await db.collection('clients').get();return s.docs.map(d=>({id:d.id,...d.data()}));}
async function getClientAllOrders(clientId){const s=await db.collection('orders').where('client_id','==',clientId).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
async function incrementClientOrderCount(id){await db.collection('clients').doc(id).update({orders_this_month:admin.firestore.FieldValue.increment(1),updated_at:now()});}
async function incrementClientFakeCaught(id){try{await db.collection('clients').doc(id).update({all_time_fake_caught:admin.firestore.FieldValue.increment(1),updated_at:now()});}catch(e){logger.error('incrementClientFakeCaught failed',e);}}
async function resetAllOrderCounts(){const s=await db.collection('clients').get(),batch=db.batch();s.docs.forEach(d=>batch.update(d.ref,{orders_this_month:0,usage_alert_80_sent:false,updated_at:now()}));await batch.commit();}

async function createOrder(data){const expires=new Date(Date.now()+24*60*60*1000);const status=data.status||'pending';const r=await db.collection('orders').add({client_id:data.client_id,store_name:data.store_name,buyer_phone:data.buyer_phone,buyer_email:data.buyer_email||null,buyer_name:data.buyer_name||null,buyer_city:data.buyer_city||null,buyer_address:data.buyer_address||null,order_id:data.order_id,order_details:data.order_details,order_amount:data.order_amount||null,buyerRiskScore:data.buyerRiskScore||null,status,whatsapp_sent:false,whatsapp_status:status==='blacklisted'?'skipped':'pending',email_sent:false,email_status:status==='blacklisted'?'skipped':'pending',confirmation_sent_at:status==='blacklisted'?null:now(),cancelReason:data.cancelReason||null,confirmed_at:null,cancelled_at:status==='blacklisted'?now():null,expires_at:fromDate(expires),created_at:now(),wa_phone_number_id:data.wa_phone_number_id||null});return r.id;}
async function getOrderById(id){const d=await db.collection('orders').doc(id).get();return d.exists?{id:d.id,...d.data()}:null;}
async function updateOrderStatus(id,status,extra={}){const u={status,...extra};if(status==='confirmed')u.confirmed_at=now();if(status==='cancelled'||status==='expired')u.cancelled_at=now();await db.collection('orders').doc(id).update(u);}
async function updateOrderWhatsappStatus(id,status){try{await db.collection('orders').doc(id).update({whatsapp_status:status});}catch(e){logger.error('updateOrderWhatsappStatus failed',e);}}
async function updateOrderEmailStatus(id,status){try{await db.collection('orders').doc(id).update({email_status:status});}catch(e){logger.error('updateOrderEmailStatus failed',e);}}
async function updateOrderWamid(id,wamid){try{await db.collection('orders').doc(id).update({wa_message_id:wamid});}catch(e){logger.error('updateOrderWamid failed',e);}}
async function getOrderByWamid(wamid){return firstBy('wa_message_id',wamid,'orders');}
async function getPendingOrderByPhone(phone){const s=await db.collection('orders').where('buyer_phone','==',phone).get();return s.docs.map(d=>({id:d.id,...d.data()})).filter(o=>o.status==='pending').sort((a,b)=>(b.created_at?.toMillis?.()||0)-(a.created_at?.toMillis?.()||0))[0]||null;}
async function getPendingOrderByPhoneAndClient(phone,clientId,orderId){const s=await db.collection('orders').where('buyer_phone','==',phone).get();return s.docs.map(d=>({id:d.id,...d.data()})).find(o=>o.status==='pending'&&o.client_id===clientId&&o.order_id===orderId)||null;}
async function getAnyOrderByPhoneClientAndOrderId(_phone,clientId,orderId){const s=await db.collection('orders').where('client_id','==',clientId).where('order_id','==',String(orderId)).limit(1).get();return s.empty?null:{id:s.docs[0].id,...s.docs[0].data()};}
async function hasPendingOrderForPhone(phone,clientId){const s=await db.collection('orders').where('buyer_phone','==',phone).where('status','==','pending').get();return s.docs.some(d=>d.data().client_id===clientId);}
async function getExpiredPendingOrders(){const s=await db.collection('orders').where('status','==','pending').get(),cutoff=now().toMillis();return s.docs.map(d=>({id:d.id,...d.data()})).filter(o=>(o.expires_at?.toMillis?.()||0)<cutoff);}
async function getPendingOrdersForRetry(){const s=await db.collection('orders').where('status','==','pending').where('whatsapp_sent','==',true).get(),t=Date.now();return s.docs.map(d=>({id:d.id,...d.data()})).filter(o=>!o.retry_sent&&t-(o.created_at?.toMillis?.()||0)>=4*3600000&&t-(o.created_at?.toMillis?.()||0)<=20*3600000);}
async function markOrderRetrySent(id){await db.collection('orders').doc(id).update({retry_sent:true});}
async function getClientForUsageAlert(id){return getClientById(id);}
async function markUsageAlertSent(id){await db.collection('clients').doc(id).update({usage_alert_80_sent:true});}
async function getClientOrdersSince(clientId,since,limit=500){const s=await db.collection('orders').where('client_id','==',clientId).where('created_at','>=',fromDate(since)).orderBy('created_at','desc').limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
async function getClientOrdersBetween(clientId,from,to,limit=10000){const s=await db.collection('orders').where('client_id','==',clientId).where('created_at','>=',fromDate(from)).where('created_at','<=',fromDate(to)).orderBy('created_at','desc').limit(limit).get();return s.docs.map(d=>({id:d.id,...d.data()}));}
async function getBuyerHistory(phone){const s=await db.collection('orders').where('buyer_phone','==',phone).get(),orders=s.docs.map(d=>d.data()),total=orders.length,confirmed=orders.filter(o=>o.status==='confirmed').length,cancelled=orders.filter(o=>o.status==='cancelled').length,ghosted=orders.filter(o=>o.status==='expired').length,blacklisted=orders.filter(o=>o.status==='blacklisted').length,ts=orders.map(o=>o.created_at?.toMillis?.()||0).filter(Boolean).sort((a,b)=>a-b);return{total,confirmed,cancelled,ghosted,blacklisted,confirmRate:total?Math.round(confirmed/total*100):0,firstSeen:ts.length?new Date(ts[0]).toISOString():null,lastSeen:ts.length?new Date(ts.at(-1)).toISOString():null};}

async function getSystemConfig(){const ref=db.collection('system').doc('config'),d=await ref.get();if(d.exists)return d.data();const defaults={daily_message_count:0,hourly_message_count:0,last_daily_reset:new Date().toISOString().slice(0,10),last_hourly_reset:new Date().toISOString().slice(0,16)};await ref.set(defaults);return defaults;}
async function getDailyMessageCount(){return (await getSystemConfig()).daily_message_count||0;}
async function getHourlyMessageCount(){return (await getSystemConfig()).hourly_message_count||0;}
async function incrementDailyMessageCount(){await db.collection('system').doc('config').set({daily_message_count:admin.firestore.FieldValue.increment(1)},{merge:true});}
async function incrementHourlyMessageCount(){await db.collection('system').doc('config').set({hourly_message_count:admin.firestore.FieldValue.increment(1)},{merge:true});}
async function resetDailyMessageCount(){await db.collection('system').doc('config').set({daily_message_count:0,hourly_message_count:0,last_daily_reset:new Date().toISOString().slice(0,10),last_hourly_reset:new Date().toISOString().slice(0,16)},{merge:true});}
async function resetHourlyMessageCount(){await db.collection('system').doc('config').set({hourly_message_count:0,last_hourly_reset:new Date().toISOString().slice(0,16)},{merge:true});}

async function createNotification(clientId,{type,message,orderId}){try{await db.collection('notifications').doc(clientId).collection('items').add({type,message,orderId:orderId||null,read:false,timestamp:now()});}catch(e){logger.error('createNotification failed',e);}}
async function getNotifications(clientId){try{const s=await db.collection('notifications').doc(clientId).collection('items').orderBy('timestamp','desc').limit(30).get();return s.docs.map(d=>({id:d.id,...d.data()}));}catch{return[];}}
async function markAllNotificationsRead(clientId){const s=await db.collection('notifications').doc(clientId).collection('items').where('read','==',false).get(),batch=db.batch();s.docs.forEach(d=>batch.update(d.ref,{read:true}));await batch.commit();}
async function updateOnboardingStep(clientId,step){try{await db.collection('clients').doc(clientId).update({[`onboardingSteps.${step}`]:true,updated_at:now()});}catch(e){logger.error('updateOnboardingStep failed',e);}}
function calculateRiskScore(p){if(!p||(p.totalOrders||0)===0)return'medium';if((p.ghostedOrders||0)>=1||(p.cancelledOrders||0)>=2)return'high';if((p.confirmedOrders||0)>0&&(p.ghostedOrders||0)===0)return'low';return'medium';}
async function getBuyerProfile(phone){const d=await db.collection('buyer_profiles').doc(phone).get();return d.exists?{id:d.id,...d.data()}:null;}
async function upsertBuyerProfile(phone,inc={}){try{const ref=db.collection('buyer_profiles').doc(phone),d=await ref.get(),old=d.exists?d.data():{};const p={phone,totalOrders:(old.totalOrders||0)+(inc.totalOrders||0),confirmedOrders:(old.confirmedOrders||0)+(inc.confirmedOrders||0),cancelledOrders:(old.cancelledOrders||0)+(inc.cancelledOrders||0),ghostedOrders:(old.ghostedOrders||0)+(inc.ghostedOrders||0),blacklisted:old.blacklisted||false};p.riskScore=calculateRiskScore(p);p.lastSeen=now();await ref.set(p,{merge:true});if(p.ghostedOrders>=2&&!p.blacklisted){await addToBlacklist(phone,{reason:'Auto-blacklisted: 2+ unconfirmed orders',addedBy:'system',orderCount:p.totalOrders});await ref.update({blacklisted:true});}return p;}catch(e){logger.error('upsertBuyerProfile failed',e);return null;}}
async function getBlacklistEntry(phone){const d=await db.collection('blacklist').doc(phone).get();return d.exists?{id:d.id,...d.data()}:null;}
async function addToBlacklist(phone,{reason='',addedBy='unknown',orderCount=0}={}){await db.collection('blacklist').doc(phone).set({phone,reason,addedBy,addedAt:now(),orderCount});try{await db.collection('buyer_profiles').doc(phone).update({blacklisted:true});}catch{}}
async function removeFromBlacklist(phone){await db.collection('blacklist').doc(phone).delete();try{await db.collection('buyer_profiles').doc(phone).update({blacklisted:false});}catch{}}
async function getBlacklistCount(){try{return (await db.collection('blacklist').get()).size;}catch{return 0;}}
async function createAuditLog(clientId,{orderId,previousStatus,newStatus,updatedBy,reason}){try{await db.collection('audit_logs').doc(clientId).collection('items').add({orderId,previousStatus:previousStatus||'',newStatus:newStatus||'',updatedBy:updatedBy||'manual',reason:reason||'',timestamp:now(),clientId});}catch(e){logger.error('createAuditLog failed',e);}}
async function licenseKeyExists(key){return !!(await getClientByLicenseKey(key));}

module.exports={db,PLAN_LIMITS,getClientByLicenseKey,getClientByDomain,getClientByMyshopifyDomain,getClientById,createClient,updateClientFields,getAllClients,getClientAllOrders,incrementClientOrderCount,incrementClientFakeCaught,resetAllOrderCounts,createOrder,getOrderById,updateOrderStatus,updateOrderWhatsappStatus,updateOrderEmailStatus,updateOrderWamid,getOrderByWamid,getPendingOrderByPhone,getPendingOrderByPhoneAndClient,getAnyOrderByPhoneClientAndOrderId,hasPendingOrderForPhone,getExpiredPendingOrders,getPendingOrdersForRetry,markOrderRetrySent,getClientForUsageAlert,markUsageAlertSent,getBuyerHistory,getClientOrdersSince,getClientOrdersBetween,createNotification,getNotifications,markAllNotificationsRead,updateOnboardingStep,getSystemConfig,getDailyMessageCount,getHourlyMessageCount,incrementDailyMessageCount,incrementHourlyMessageCount,resetDailyMessageCount,resetHourlyMessageCount,licenseKeyExists,calculateRiskScore,getBuyerProfile,upsertBuyerProfile,getBlacklistEntry,addToBlacklist,removeFromBlacklist,getBlacklistCount,createAuditLog};
